site_name: CWL as a solution for Earth Observation portability

theme:
    logo: assets/icon-eoap.png
    name: material

    palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
plugins:
  - search
  - mermaid2:
      version: 10.6.0

markdown_extensions:
  - pymdownx.details
  - abbr
  - admonition
  - footnotes
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - attr_list
  - pymdownx.snippets:
      base_path: './'
  - pymdownx.highlight:
      line_spans: __span
extra_css:
  - styles/css/app.css
  
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  

nav:
  - Introduction: 'index.md'
  - Background: 
    - Introduction: 'background/background.md'
    - Previous OGC Testbeds: 'background/previous-ogc-testbeds.md'
    - OGC EO Applications Pilot: 'background/applications-pilot.md'
    - Best Practice for EO Application Package: 'background/eoap-best-practice.md'
  - Common Workflow Language: 
    - CWL in a nutshell: 'cwl/nutshell.md'
    - CWL in the Best Practice for EO Application Package: 'cwl/cwl-eoap.md'
  - Understanding YAML syntax: 'yaml.md'
  - Usage Scenarios: 'usage-scenarios.md'
  - Best Practices:
    - Application Best Practices: 'best-practice/application.md'
    - Package Best Practices: 'best-practice/package.md'

copyright: Maintained by Terradue
#copyright: <a href="https://img.shields.io/badge/License-CC_BY--SA_4.0-lightgrey.svg">License CC BY-SA 4.0</a>, by <a href="https://creativecommons.org/licenses/by-sa/4.0/">Creative Commons</a>
# copyright: Copyright &copy; 2014 <a href="https://twitter.com/starletdreaming">Tom Christie</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">MkDocs Team</a>.