name: env_stac
channels:
  - terradue
  - conda-forge
dependencies:
  - python=3.11
  - pip:
    - cwltool
    - pystac
    - stactools
    - rasterio 
    - requests 
    - stac-asset 
    - click-logging 
    - tabulate 
    - tqdm 
    - pystac-client 
    - ipykernel
    - scikit-image
    - loguru
    - mkdocs-material
    - mkdocs-mermaid2-plugin